name: Test Snap Build
description: Build the snap locally using Snapcraft and review the output.
author: Snapcrafters
branding:
  icon: zap
  color: orange

inputs:
  install:
    description: "Option to install the snap on the runner after build"
    default: "false"
    required: false
  snapcraft-yaml-path:
    description: "Custom path to snapcraft.yaml for when it is not in the default location."
    required: false

runs:
  using: composite
  steps:
    - name: Checkout the source
      uses: actions/checkout@v4

    - name: Find and parse snapcraft.yaml
      id: snapcraft-yaml
      uses: snapcrafters/ci/parse-snapcraft-yaml@main
      with:
        snapcraft-yaml-path: ${{ inputs.snapcraft-yaml-path }}

    - name: Build snap
      uses: snapcore/action-build@v1
      id: build
      with:
        path: ${{ steps.snapcraft-yaml.outputs.yaml-path }}

    - name: Review the built snap
      uses: diddlesnaps/snapcraft-review-action@v1
      with:
        snap: ${{ steps.build.outputs.snap }}
        isClassic: ${{ steps.snapcraft-yaml.outputs.classic }}
        plugs: ${{ steps.snapcraft-yaml.outputs.plugs-file }}
        slots: ${{ steps.snapcraft-yaml.outputs.slots-file }}

    - name: Install the snap
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: |
        sudo snap install --classic --dangerous "${{ steps.build.outputs.snap }}"
