name: Sync Version
description: Sync versions of a snap's applications and parts with the latest upstream versions.
author: Snapcrafters
branding:
  icon: refresh-cw
  color: orange

inputs:
  update-script:
    description: "Bash script that fetches the latest version and updates the source tree as required."
    required: true
  token:
    required: true
    description: A token with write privileges to the repository.
  snapcraft-yaml-path:
    description: "Custom path to snapcraft.yaml for when it is not in the default location."
    required: false

runs:
  using: composite
  steps:
    - name: Checkout the source
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Find the snapcraft.yaml path
      id: yaml-path
      shell: bash
      run: |
        if [[ -n "${{ inputs.snapcraft-yaml-path }}"; then
          yaml-path="${{ inputs.snapcraft-yaml-path }}"
        else
          snapcraft-yaml-paths=(
            "snap/snapcraft.yaml"
            "snapcraft.yaml"
            "build-aux/snap/snapcraft.yaml"
            ".snapcraft.yaml"
          )
          
          for file in "${snapcraft-yaml-paths[@]}"; do
              if [[ -f "$file" ]]; then
                  yaml-path="$file"
              fi
          done
        fi
        if [[ ! -n "${yaml-path}" ]]; then
           echo "No snapcraft.yaml found" >2
           exit 1
        fi
        echo "yaml-path=${yaml-path}" >> "$GITHUB_OUTPUT"
        echo "snap-name=$(yq -r '.name' "$yaml-path")" >> "$GITHUB_OUTPUT"
        echo "prev_version=$(yq -r '.version' "$yaml-path")" >> "$GITHUB_OUTPUT"

    - name: Run update script
      shell: bash
      run: |
        ${{ inputs.update-script }}

    - name: Check for modified files
      shell: bash
      id: git-check
      run: |
        MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        echo "modified=$MODIFIED" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.git-check.outputs.modified == 'true'
      shell: bash
      with:
        yaml-path: ${{ steps.yaml-path.outputs.yaml-path }}
        prev_version: ${{ steps.yaml-path.outputs.prev_version }}
      env:
        SNAP_NAME: ${{ steps.yaml-path.outputs.snap-name || github.event.repository.name }}
      run: |
        new_version="$(yq -r '.version' "$yaml-path")"
        if [[ ! "$prev_version" == "$new_version" ]]; then
            version=$new_version
        fi
        git config --global user.name 'Snapcrafters Bot'
        git config --global user.email 'merlijn.sebrechts+snapcrafters-bot@gmail.com'
        if [[ -n "${version:-}" ]]; then
            git commit -am "chore: bump ${SNAP_NAME} to version $version"
        else
            git commit -am "chore: bump ${SNAP_NAME} dependencies"
        fi
        git push
