name: Setup ghvmctl
description: Configure a runner for access to the KVM socket and install ghvmctl
author: Snapcrafters
branding:
  icon: refresh-cw
  color: orange

inputs:
  update-script:
    description: "Bash script that fetches the latest version and updates the source tree as required."
    required: true
  token:
    required: true
    description: A token with write privileges to the repository.
  yaml-path:
    description: "Custom path to snapcraft.yaml allowing to have multiple manifests in one repo."
    required: false

runs:
  using: composite
  steps:
    - name: Checkout the source
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Run update script
      shell: bash
      run: |
        ${{ inputs.update-script }}

    - name: Check for modified files
      shell: bash
      id: git-check
      run: |
        MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        echo "modified=$MODIFIED" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.git-check.outputs.modified == 'true'
      shell: bash
      env:
        SNAP_NAME: ${{ github.event.repository.name }}
      run: |
        if [ -n "${{ inputs.yaml-path }}" ]; then
            yaml_path="${{ inputs.yaml-path }}"
        elif [ -e snap/snapcraft.yaml ]; then
            yaml_path="snap/snapcraft.yaml"
        elif [ -e snapcraft.yaml ]; then
            yaml_path="snapcraft.yaml"
        elif [ -e build-aux/snap/snapcraft.yaml ]; then
            yaml_path="build_aux/snap/snapcraft.yaml"
        elif [ -e .snapcraft.yaml ]; then
            yaml_path=.snapcraft.yaml
        else
            echo "Could not find snapcraft.yaml"
            exit 1
        fi
        version="$(cat $yaml_path | yq -r '.version')"
        git config --global user.name 'Snapcrafters Bot'
        git config --global user.email 'merlijn.sebrechts+snapcrafters-bot@gmail.com'
        git commit -am "chore: bump ${SNAP_NAME} to version $version"
        git push
