name: Sync Version
description: Sync the version with latest upstream releases
author: Snapcrafters
branding:
  icon: refresh-cw
  color: orange

inputs:
  update-script:
    description: "Bash script that fetches the latest version and updates the source tree as required."
    required: true
  token:
    required: true
    description: A token with write privileges to the repository.
  snapcraft-yaml-path:
    description: "Custom path to snapcraft.yaml for when it is not in the default location."
    required: false

runs:
  using: composite
  steps:
    - name: Checkout the source
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Find the snapcraft.yaml path
      id: yaml-path
      shell: bash
      run: |
        if [[ -n "${{ inputs.snapcraft-yaml-path }}"; then
          yaml_path="${{ inputs.snapcraft-yaml-path }}"
        else
          snapcraft_yaml_paths=(
          "snap/snapcraft.yaml"
          "snapcraft.yaml"
          "build-aux/snap/snapcraft.yaml"
          ".snapcraft.yaml"
          )
          
        for file in "${snapcraft_yaml_paths[@]}"; do
            if [[ -f "$file" ]]; then
                yaml_path="$file"
            fi
        done
        fi
        echo "yaml_path=${yaml_path}" >> "$GITHUB_OUTPUT"
        echo "prev_version=$(yq -r '.version' $yaml_path)" >> "$GITHUB_OUTPUT"

    - name: Run update script
      shell: bash
      run: |
        ${{ inputs.update-script }}

    - name: Check for modified files
      shell: bash
      id: git-check
      run: |
        MODIFIED=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
        echo "modified=$MODIFIED" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.git-check.outputs.modified == 'true'
      shell: bash
      with:
        yaml_path: ${{ steps.yaml-path.outputs.yaml_path }}
        prev_version: ${{ steps.yaml-path.outputs.prev_version }}
      env:
        SNAP_NAME: ${{ github.event.repository.name }}
      run: |
        new_version="$(yq -r '.version' $yaml_path)"
        if [[ ! "$prev_version" -eq "$new_version" ]]; then
            version=$new_version
        fi
        git config --global user.name 'Snapcrafters Bot'
        git config --global user.email 'merlijn.sebrechts+snapcrafters-bot@gmail.com'
        if [ $version ]; then
            git commit -am "chore: bump ${SNAP_NAME} to version $version"
        else
            git commit -am "chore: bump ${SNAP_NAME} dependencies"
        fi
        git push
